### ISSUE TITLE
There is a bug!!

### ISSUE THREAD

**Issue by stocks29** [bkirkby/ConsumablePriceIndex#1]
This is written in go. Rewrite in something else to fix this bug :P

hehe, jk

Seriously though, this is pretty sweet! Awesome job! ... and encrypted properties to boot! :)

**Comment by bkirkby** [comment]
:+1: thanks man. i just need to finish the server and then i'll have it start collecting data. at some point in the future i'll have a website where i can explore the data as well as an alert system to let me know about great deals.

closing out this issue tho as it's going to remain Go :smile:
